name: releaser

on:
  push:
    tags:
      - "*"

jobs:
  releaser:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        shell: pwsh
        run: |
          mkdir ..\build
          .\InsertEnvLoad.exe
          go build -o ../build/automuteus.exe -ldflags `
            ' `
              -X main.version=$(git describe --tags \"$(git rev-list --tags --max-count=1)\") `
              -X main.commit=$(git rev-parse --short HEAD) `
            ' main.go load.go

      - name: Collecting assets
        shell: pwsh
        run: |
          mkdir ..\build\locales, ..\build\storage
          copy locales\*.toml ..\build\locales\
          copy storage\postgres.sql ..\build\storage\postgres.sql

      - name: Zip files
        shell: pwsh
        run: |
          Compress-Archive -Path ..\build\* -DestinationPath ..\build\automuteus.zip

      - name: Create the hashes.txt
        shell: pwsh
        run: |
          (Get-ChildItem ..\build\ -Recurse -File -Force -ea SilentlyContinue -ev errs | Get-FileHash -Algorithm SHA256 | Format-Table Hash, @{Label="Path"; Expression={((Resolve-Path -Relative $_.Path) -replace '..\\build\\','') -replace '\\','/'}} -HideTableHeaders | Out-String).Trim() | Out-File -FilePath ..\build\hashes.txt

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ..\build\automuteus.zip
            ..\build\hashes.txt